travis:
  secure:
    BINSTAR_TOKEN: LupYexD9c6pY9OoOdMRwFTHj3tv+VArpoHncRH7BsOhmqoWek1dSV8qoQHgzeEQ1ef/1r394xAOph1+bxxYx4uMZbckZkBLMfaNrN8yEIcjw8aG+U2fSmpt0qGHD4kI7xCuqUkiNCScgBaJBdAmtPyQ2tnmsBrnAextF1bGxoFEUJMVY43rjRZkdlfvd1jxorEnCnfkrmdJ2AOciuoMWlv5rY6MNR/gVpLoCqYEeSjmZCCrs0q2KowW8KPhC0EU6EzjsKOFhe5n5tHJOQq3pGmftGYwuwD2AOP1kzahBttEbrqGWNlyV5Gg8Tgml9jwi8fyY1nSKcwVXE1HD4ZeGkk/C36EaW8avd07yJnhoOmvhF3ctyFnD37RfFLUX2zrLpFLLv5QzIV3JcNtN+uaD05jDRMa5lP4bztjNlLun9e3FhcmLK1/pO8j/jGGtrvQN8JivC0YvD1L2eXmTkVIn2dMUaDRV0ab4vsdolMVjm8G7T/Tx4DElL88d6v3liYEdOg8+swcytMiEs3HlEfZQrpHRlgVWAKOuvwQtyqQieVudrHJz4XN5W0UdUFJ5HK2xQiCdWcxczqI87o1cUp2sIF4Z05v8JRDOLEZJL6wlHrwTtnqp9oS9GfhjSzuchqwjxGfv22v0xSGHiQR5kw0Q9YlAcq93fwgmOPQW8BFl9ks=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
